version: '3.8'

services:
  banco_postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_sistema_bancario
      POSTGRES_USER: sys
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
