# Generated by Django 5.0.6 on 2024-05-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('cpf', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('limite_saques', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transacao', models.CharField(choices=[('d', 'deposito'), ('s', 'saque')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('agencia', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_bancario_app.cliente')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_bancario_app.historico')),
            ],
        ),
    ]
