# Generated by Django 5.0.6 on 2024-05-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_bancario_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
