# Generated by Django 5.0.6 on 2024-05-23 18:31

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_bancario_app', '0002_historico_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, unique=True),
        ),
    ]
