# Generated by Django 5.0.6 on 2024-05-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_bancario_app', '0003_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='conta_realizou',
            field=models.ManyToManyField(related_name='+', to='sistema_bancario_app.conta'),
        ),
    ]
