# Generated by Django 5.0.6 on 2024-05-24 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_bancario_app', '0004_historico_conta_realizou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='historico',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='conta_realizou',
        ),
        migrations.AddField(
            model_name='contacorrente',
            name='conta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_bancario_app.conta'),
        ),
        migrations.AddField(
            model_name='historico',
            name='conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='sistema_bancario_app.conta'),
        ),
        migrations.AddField(
            model_name='historico',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='tipo_transacao',
            field=models.CharField(choices=[('d', 'Depósito'), ('s', 'Saque')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
