# Generated by Django 5.0.6 on 2024-05-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_bancario_app', '0005_remove_conta_historico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacorrente',
            name='conta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema_bancario_app.conta'),
        ),
    ]
